# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.49
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.set_tag_object import SetTagObject  # noqa: E501
from swagger_client.rest import ApiException


class TestSetTagObject(unittest.TestCase):
    """SetTagObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetTagObject(self):
        """Test SetTagObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.set_tag_object.SetTagObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
