# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.40
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.category_search_request_v1 import CategorySearchRequestV1  # noqa: E501
from swagger_client.rest import ApiException


class TestCategorySearchRequestV1(unittest.TestCase):
    """CategorySearchRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategorySearchRequestV1(self):
        """Test CategorySearchRequestV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.category_search_request_v1.CategorySearchRequestV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
