# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.47
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.es_completion_suggest import EsCompletionSuggest  # noqa: E501
from swagger_client.rest import ApiException


class TestEsCompletionSuggest(unittest.TestCase):
    """EsCompletionSuggest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEsCompletionSuggest(self):
        """Test EsCompletionSuggest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.es_completion_suggest.EsCompletionSuggest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
