# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.49
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.link_graph_response import LinkGraphResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestLinkGraphResponse(unittest.TestCase):
    """LinkGraphResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkGraphResponse(self):
        """Test LinkGraphResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.link_graph_response.LinkGraphResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
