# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.39
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.set_designs_tags_response import SetDesignsTagsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestSetDesignsTagsResponse(unittest.TestCase):
    """SetDesignsTagsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetDesignsTagsResponse(self):
        """Test SetDesignsTagsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.set_designs_tags_response.SetDesignsTagsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
