# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.47
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.trending_request import TrendingRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestTrendingRequest(unittest.TestCase):
    """TrendingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrendingRequest(self):
        """Test TrendingRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.trending_request.TrendingRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
