# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.40
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.related_api import RelatedApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRelatedApi(unittest.TestCase):
    """RelatedApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.related_api.RelatedApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_v1_related_search(self):
        """Test case for get_v1_related_search

        Gets related searches based on given term  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
