# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.relevancy_api import RelevancyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRelevancyApi(unittest.TestCase):
    """RelevancyApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.relevancy_api.RelevancyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_v1_relevancy_configuration(self):
        """Test case for delete_v1_relevancy_configuration

        Deletes search relevancy configuration.  # noqa: E501
        """
        pass

    def test_get_v1_relevancy_configuration(self):
        """Test case for get_v1_relevancy_configuration

        Gets a search relevancy configuration.  # noqa: E501
        """
        pass

    def test_get_v1_relevancy_configurations(self):
        """Test case for get_v1_relevancy_configurations

        Gets all relevancy configurations.  # noqa: E501
        """
        pass

    def test_post_v1_relevancy_configurations(self):
        """Test case for post_v1_relevancy_configurations

        Saves search relevancy configuration.  # noqa: E501
        """
        pass

    def test_put_v1_relevancy_configuration(self):
        """Test case for put_v1_relevancy_configuration

        Updates search relevancy configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
