# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.48
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.service_api import ServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.service_api.ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_healthcheck_get(self):
        """Test case for healthcheck_get

        Check if the service is running  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
