# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.24
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tag_mapping_response import TagMappingResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestTagMappingResponse(unittest.TestCase):
    """TagMappingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagMappingResponse(self):
        """Test TagMappingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tag_mapping_response.TagMappingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
