# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.48
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.autocomplete_suggestion import AutocompleteSuggestion  # noqa: E501
from swagger_client.rest import ApiException


class TestAutocompleteSuggestion(unittest.TestCase):
    """AutocompleteSuggestion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutocompleteSuggestion(self):
        """Test AutocompleteSuggestion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.autocomplete_suggestion.AutocompleteSuggestion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
