# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.47
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.similar_designs_response import SimilarDesignsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestSimilarDesignsResponse(unittest.TestCase):
    """SimilarDesignsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimilarDesignsResponse(self):
        """Test SimilarDesignsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.similar_designs_response.SimilarDesignsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
