# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lookup_api import LookupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLookupApi(unittest.TestCase):
    """LookupApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.lookup_api.LookupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_v1_lookup_by_id(self):
        """Test case for get_v1_lookup_by_id

        Returns a published designs based on id.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
