# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.admin_api import AdminApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.admin_api.AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_v1_admin_relevancy(self):
        """Test case for post_v1_admin_relevancy

        Saves search relevancy configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
