# coding: utf-8

# flake8: noqa
"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.45
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.artist_search_request import ArtistSearchRequest
from swagger_client.models.autocomplete_request import AutocompleteRequest
from swagger_client.models.autocomplete_response import AutocompleteResponse
from swagger_client.models.autocomplete_suggestion import AutocompleteSuggestion
from swagger_client.models.design import Design
from swagger_client.models.design_slim import DesignSlim
from swagger_client.models.design_tags_response import DesignTagsResponse
from swagger_client.models.dmca_search_request_v2 import DmcaSearchRequestV2
from swagger_client.models.es_autocomplete_suggest import EsAutocompleteSuggest
from swagger_client.models.es_completion_suggest import EsCompletionSuggest
from swagger_client.models.es_completion_suggest_option import EsCompletionSuggestOption
from swagger_client.models.es_hit import EsHit
from swagger_client.models.es_hits import EsHits
from swagger_client.models.es_search_response import EsSearchResponse
from swagger_client.models.explain import Explain
from swagger_client.models.link_graph_response import LinkGraphResponse
from swagger_client.models.related_response import RelatedResponse
from swagger_client.models.related_result import RelatedResult
from swagger_client.models.related_tag_object import RelatedTagObject
from swagger_client.models.related_tag_response import RelatedTagResponse
from swagger_client.models.related_tag_result import RelatedTagResult
from swagger_client.models.search_request import SearchRequest
from swagger_client.models.search_request_v2 import SearchRequestV2
from swagger_client.models.search_response import SearchResponse
from swagger_client.models.set_design_taggings_object import SetDesignTaggingsObject
from swagger_client.models.set_designs_taggings_request import SetDesignsTaggingsRequest
from swagger_client.models.set_designs_tags_response import SetDesignsTagsResponse
from swagger_client.models.set_link_graph_request import SetLinkGraphRequest
from swagger_client.models.set_link_graph_response import SetLinkGraphResponse
from swagger_client.models.set_tag_object import SetTagObject
from swagger_client.models.set_tags_request import SetTagsRequest
from swagger_client.models.set_tags_response import SetTagsResponse
from swagger_client.models.similar_designs_request_v1 import SimilarDesignsRequestV1
from swagger_client.models.similar_designs_response import SimilarDesignsResponse
from swagger_client.models.tag_result import TagResult
from swagger_client.models.tags_response import TagsResponse
from swagger_client.models.trending_request import TrendingRequest
from swagger_client.models.trending_result import TrendingResult
