# coding: utf-8

"""
    TeePublic V3 search Api Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.24
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TagMappingResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'child_tag': 'str',
        'parent_tag': 'str'
    }

    attribute_map = {
        'child_tag': 'child_tag',
        'parent_tag': 'parent_tag'
    }

    def __init__(self, child_tag=None, parent_tag=None):  # noqa: E501
        """TagMappingResponse - a model defined in Swagger"""  # noqa: E501

        self._child_tag = None
        self._parent_tag = None
        self.discriminator = None

        if child_tag is not None:
            self.child_tag = child_tag
        if parent_tag is not None:
            self.parent_tag = parent_tag

    @property
    def child_tag(self):
        """Gets the child_tag of this TagMappingResponse.  # noqa: E501

        child tag  # noqa: E501

        :return: The child_tag of this TagMappingResponse.  # noqa: E501
        :rtype: str
        """
        return self._child_tag

    @child_tag.setter
    def child_tag(self, child_tag):
        """Sets the child_tag of this TagMappingResponse.

        child tag  # noqa: E501

        :param child_tag: The child_tag of this TagMappingResponse.  # noqa: E501
        :type: str
        """

        self._child_tag = child_tag

    @property
    def parent_tag(self):
        """Gets the parent_tag of this TagMappingResponse.  # noqa: E501

        parent tag  # noqa: E501

        :return: The parent_tag of this TagMappingResponse.  # noqa: E501
        :rtype: str
        """
        return self._parent_tag

    @parent_tag.setter
    def parent_tag(self, parent_tag):
        """Sets the parent_tag of this TagMappingResponse.

        parent tag  # noqa: E501

        :param parent_tag: The parent_tag of this TagMappingResponse.  # noqa: E501
        :type: str
        """

        self._parent_tag = parent_tag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TagMappingResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TagMappingResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
